"""add column age to DeliveryBoy

Revision ID: 8d6bd2b65438
Revises: 07bc378c3a06
Create Date: 2023-12-11 21:15:21.991201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6bd2b65438'
down_revision: Union[str, None] = '07bc378c3a06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_boy', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_boy', 'age')
    # ### end Alembic commands ###
