"""create order service models

Revision ID: 83144edc2126
Revises: a70fd8a1c681
Create Date: 2023-12-13 21:10:17.107462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83144edc2126'
down_revision: Union[str, None] = 'a70fd8a1c681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('delivery_boy_id', sa.Integer(), nullable=True),
    sa.Column('items', sa.String(length=30), nullable=False),
    sa.Column('delivery_status', sa.Enum('confirmed', 'collect', 'handed', 'delive', name='delivestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delivery_boy_id'], ['delivery_boy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('customers')
    # ### end Alembic commands ###
