"""empty message

Revision ID: 684222a959c6
Revises: 83144edc2126
Create Date: 2024-01-08 20:54:29.627423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '684222a959c6'
down_revision: Union[str, None] = '83144edc2126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('customers')
    op.drop_table('delivery_boy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_boy',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('delivery_boy_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='delivery_boy_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('customers',
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('customers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='customers_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('orders',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_boy_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('items', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('delivery_status', postgresql.ENUM('confirmed', 'collect', 'handed', 'delive', name='delivestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='orders_customer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delivery_boy_id'], ['delivery_boy.id'], name='orders_delivery_boy_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey')
    )
    # ### end Alembic commands ###
